# Generated by Django 3.0.4 on 2020-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
