# Generated by Django 3.0.4 on 2020-06-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.TextField(default='Empty', max_length=30),
        ),
    ]
