# Generated by Django 3.0.4 on 2020-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_auto_20200602_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.TextField(default='in progress', max_length=30),
        ),
    ]
