# Generated by Django 3.0.4 on 2020-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_auto_20200602_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
