# Generated by Django 3.0.4 on 2020-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_auto_20200610_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nature',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='path',
            field=models.CharField(max_length=255, unique=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
