# Generated by Django 3.0.4 on 2020-06-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_auto_20200617_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
