# Generated by Django 3.0.4 on 2020-07-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_auto_20200629_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='function',
        ),
    ]
