# Generated by Django 3.0.4 on 2021-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0015_auto_20210527_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='end_date',
        ),
        migrations.AddField(
            model_name='process',
            name='financial_level_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='financial_level_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='financial_level_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='financial_level_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='financial_level_5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
