# Generated by Django 3.0.4 on 2021-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0016_auto_20210625_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
