# Generated by Django 3.0.4 on 2021-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('headers', models.CharField(blank=True, max_length=3000, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=3)),
                ('statusText', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=3000, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
