# Generated by Django 3.0.4 on 2021-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20210508_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='timestamp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
