# Generated by Django 3.0.4 on 2021-06-15 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_datalog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='path',
            field=models.CharField(default=1, max_length=255,unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='structure',
            field=models.CharField(choices=[('Dashboard', 'Dashboard'), ('Process', 'Process'), ('Risk', 'Risk'), ('Setting', 'Setting')], max_length=50),
        ),
    ]
