# Generated by Django 3.0.4 on 2021-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20210615_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
