# Generated by Django 3.0.4 on 2021-12-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_auto_20211225_1121'),
        ('permissions', '0006_auto_20211225_0923'),
    ]

    operations = [
    ]
